import {describe,expect,it} from 'vitest';
import JSZip from 'jszip';
import {createRequestZip,makePrompt,parseResultBundle,RequestSchema,ResultSchema} from './protocol';

const request=()=>RequestSchema.parse({schemaVersion:'1.0.0',app:'shinra-bansho-kan',subject:{name:'試験 花子',birthDate:'2000-01-02',birthTime:null,birthTimePrecision:'unknown',birthPlace:{country:'日本'}},questions:['仕事'],freeformQuestion:'',requestedSystems:['western_astrology'],options:{crossAnalysis:true,showCalculations:true,showUncertainty:true,generateSummaryImage:true}});
const result=()=>({schemaVersion:'1.0.0',subject:{name:'試験 花子'},meta:{},baseInfo:{},systems:[{id:'western_astrology',name:'西洋占星術',status:'partial',inputsUsed:['生年月日'],calculations:[],facts:[],interpretation:['試験結果'],uncertainties:['時刻不明'],sources:[]}],crossAnalysis:{strongThemes:['テーマ'],moderateThemes:[],contradictions:[],dependencyWarnings:['同じ入力に依存']},domainProfiles:{},summary:{headline:'読みの見出し',text:'説明'},limitations:[],assets:{}});
const png=Uint8Array.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d]);
const webp=Uint8Array.from([0x52,0x49,0x46,0x46,0x04,0x00,0x00,0x00,0x57,0x45,0x42,0x50]);
const asFile=async(zip:JSZip,name='result.zip')=>new File([await zip.generateAsync({type:'blob'})],name,{type:'application/zip'});

describe('portable package protocol',()=>{
 it('puts relaxed image-failure and dimension rules in the request ZIP',async()=>{const r=request();const prompt=makePrompt(r,{western_astrology:'西洋占星術'});expect(prompt).toContain('西洋占星術');const zip=await JSZip.loadAsync(await createRequestZip(r,prompt,new Date('2026-09-24T00:00:00Z')));const files=Object.keys(zip.files).filter(x=>!zip.files[x].dir);expect(files).toContain('schema/request.schema.json');expect(files).toContain('schema/result.schema.json');expect(RequestSchema.parse(JSON.parse(await zip.file('request.json')!.async('text'))).subject.birthTime).toBeNull();const instructions=await zip.file('instructions.md')!.async('text');expect(instructions).toContain('画像生成は任意');expect(instructions).toContain('サイズ不一致だけを理由に');expect(instructions).toContain('画像がない結果もスキーマ適合の有効な鑑定結果です');});
 it('keeps copy mode in-chat while requesting a best-effort card',async()=>{const r=request();const names={western_astrology:'西洋占星術'};const packagePrompt=makePrompt(r,names);const markdownPrompt=makePrompt(r,names,'markdown');expect(packagePrompt).toContain('画像生成は任意');expect(markdownPrompt).toContain('ChatGPT完結');expect(markdownPrompt).toContain('画像なしで完了');expect(markdownPrompt).toContain('JSON、JSONコードブロック、manifest、ZIPは作成しません');expect(markdownPrompt).not.toContain('manifest.json');const zip=await JSZip.loadAsync(await createRequestZip(r,packagePrompt));expect(Object.keys(zip.files).filter(x=>!zip.files[x].dir)).toContain('schema/result.schema.json');});
 it('reads a legacy result ZIP with a raster card and repairs object-shaped calculations',async()=>{const value=result();(value.systems[0] as any).calculations={method:'tropical',value:'sun sign'};const zip=new JSZip();zip.file('result.json',JSON.stringify(value));zip.file('report.md','# Full Report\n\nLong form reading.');zip.file('manifest.json',JSON.stringify({format:'shinra-bansho-result',version:'1.0.0'}));zip.file('assets/summary.png',png);zip.file('assets/share.png',png);const loaded=await parseResultBundle(await asFile(zip));expect(loaded.summary).toEqual(value.summary);expect(loaded.systems[0].calculations).toEqual([{label:'method',value:'tropical'},{label:'value',value:'sun sign'}]);expect((loaded.meta as any).importWarnings).toHaveLength(1);expect((loaded as any).reportMarkdown).toContain('Long form reading');expect(loaded.assets.summaryImage).toMatch(/^data:image\/png;base64,/);expect(loaded.assets.shareImage).toMatch(/^data:image\/png;base64,/);});
 it('imports a nested no-image ZIP and accepts object collections plus size-mismatched raster cards',async()=>{const value=result();(value.systems[0] as any).calculations={method:'tropical'};(value.systems[0] as any).facts={sun:'Aries'};(value.crossAnalysis as any).strongThemes={theme:'independent decisions'};value.assets={shareImage:'assets/share.png',shareGeneration:{status:'unavailable',message:'image tool unavailable'}};const zip=new JSZip();zip.file('package/result.json',JSON.stringify(value));zip.file('package/report.md','# Complete report');zip.file('package/manifest.json',JSON.stringify({format:'foreign-result-wrapper',version:'2026'}));const loaded=await parseResultBundle(await asFile(zip));expect(loaded.systems[0].calculations).toEqual([{label:'method',value:'tropical'}]);expect(loaded.systems[0].facts).toEqual([{label:'sun',value:'Aries'}]);expect(loaded.crossAnalysis.strongThemes).toEqual([{label:'theme',value:'independent decisions'}]);expect(loaded.assets.shareImage).toBeUndefined();expect((loaded.meta as any).importWarnings.length).toBeGreaterThan(1);
 const withCard=result();withCard.assets={shareImage:'package/assets/my-card.webp',shareGeneration:{status:'generated',width:1024,height:1024,provider:'Other AI',model:'native-image'}};const zipWithCard=new JSZip();zipWithCard.file('package/result.json',JSON.stringify(withCard));zipWithCard.file('package/report.md','# Complete report');zipWithCard.file('package/assets/my-card.webp',webp);const loadedCard=await parseResultBundle(await asFile(zipWithCard));expect(loadedCard.assets.shareImage).toMatch(/^data:image\/webp;base64,/);expect((loadedCard.assets.shareGeneration as any).width).toBe(1024);});
 it('imports a standalone result JSON without a share image',async()=>{const value=result();value.assets={shareGeneration:{status:'failed'}};const loaded=await parseResultBundle(new File([JSON.stringify(value)],'result.json',{type:'application/json'}));expect(loaded.assets.shareImage).toBeUndefined();expect(ResultSchema.parse(loaded).systems).toHaveLength(1);});
 it('rejects request packages and unsupported result schema major versions',async()=>{const requestZip=new JSZip();requestZip.file('request.json','{}');await expect(parseResultBundle(await asFile(requestZip,'request.zip'))).rejects.toThrow('鑑定依頼ZIP');const bad=result();bad.schemaVersion='2.0.0';await expect(parseResultBundle(new File([JSON.stringify(bad)],'result.json'))).rejects.toThrow('未対応');});
 it('reports malformed and missing result files',async()=>{const empty=new JSZip();empty.file('report.md','# no result');await expect(parseResultBundle(await asFile(empty,'empty.zip'))).rejects.toThrow('result.json');const malformed=new JSZip();malformed.file('result.json','{broken');await expect(parseResultBundle(await asFile(malformed,'broken.zip'))).rejects.toThrow();});
});
