import {describe,expect,it} from 'vitest';
import JSZip from 'jszip';
import {createRequestZip,makePrompt,parseResultBundle,RequestSchema,ResultSchema} from './protocol';

const request=()=>RequestSchema.parse({schemaVersion:'1.0.0',app:'shinra-bansho-kan',subject:{name:'試験 花子',birthDate:'2000-01-02',birthTime:null,birthTimePrecision:'unknown',birthPlace:{country:'日本'}},questions:['仕事'],freeformQuestion:'',requestedSystems:['western_astrology'],options:{crossAnalysis:true,showCalculations:true,showUncertainty:true,generateSummaryImage:true}});
const result={schemaVersion:'1.0.0',subject:{name:'試験 花子'},meta:{},baseInfo:{},systems:[{id:'western_astrology',name:'西洋占星術',status:'partial',inputsUsed:['生年月日'],calculations:[],facts:[],interpretation:['試験結果'],uncertainties:['時刻不明'],sources:[]}],crossAnalysis:{strongThemes:['テーマ'],moderateThemes:[],contradictions:[],dependencyWarnings:['同じ入力に依存']},domainProfiles:{},summary:{headline:'読みの見出し',text:'説明'},limitations:[],assets:{}};

describe('portable package protocol',()=>{
 it('validates request data and produces a self-contained request ZIP',async()=>{const r=request();const prompt=makePrompt(r,{western_astrology:'西洋占星術'});expect(prompt).toContain('出生時刻');expect(prompt).toContain('西洋占星術');const blob=await createRequestZip(r,prompt,new Date('2026-09-24T00:00:00Z'));const zip=await JSZip.loadAsync(blob);expect(Object.keys(zip.files).filter(x=>!zip.files[x].dir).sort()).toEqual(['README.md','instructions.md','manifest.json','prompt.md','request.json','schema/request.schema.json'].sort());const saved=JSON.parse(await zip.file('request.json')!.async('text'));expect(RequestSchema.parse(saved).subject.birthTime).toBeNull();expect(JSON.parse(await zip.file('manifest.json')!.async('text')).format).toBe('shinra-bansho-request');});
 it('validates and reads result ZIP including an optional image asset',async()=>{expect(ResultSchema.parse(result).systems).toHaveLength(1);const zip=new JSZip();zip.file('result.json',JSON.stringify(result));zip.file('report.md','# Report');zip.file('manifest.json',JSON.stringify({format:'shinra-bansho-result',version:'1.0.0'}));zip.file('assets/summary.png','fixture-image');const blob=await zip.generateAsync({type:'blob'});const file=new File([blob],'result.zip',{type:'application/zip'});const loaded=await parseResultBundle(file);expect(loaded.summary).toEqual(result.summary);expect(loaded.assets.summaryImage).toMatch(/^data:image\/png;base64,/);});
 it('rejects a request package when a result is expected and rejects unsupported major versions',async()=>{const zip=new JSZip();zip.file('request.json','{}');const file=new File([await zip.generateAsync({type:'blob'})],'request.zip');await expect(parseResultBundle(file)).rejects.toThrow('鑑定依頼ZIP');const bad=new JSZip();bad.file('result.json',JSON.stringify(result));bad.file('manifest.json',JSON.stringify({format:'shinra-bansho-result',version:'2.0.0'}));await expect(parseResultBundle(new File([await bad.generateAsync({type:'blob'})],'result.zip'))).rejects.toThrow('未対応');});
 it('reports malformed and incomplete result payloads',async()=>{const empty=new JSZip();empty.file('report.md','# no result');await expect(parseResultBundle(new File([await empty.generateAsync({type:'blob'})],'empty.zip'))).rejects.toThrow('result.json');const malformed=new JSZip();malformed.file('result.json','{broken');await expect(parseResultBundle(new File([await malformed.generateAsync({type:'blob'})],'broken.zip'))).rejects.toThrow();});
});
