import JSZip from 'jszip';
import { z } from 'zod';

export const RequestSchema = z.object({
  schemaVersion:z.string(), app:z.literal('shinra-bansho-kan'), mode:z.enum(['individual','compatibility']).default('individual'),
  subject:z.object({name:z.string(),nameKana:z.string().optional(),romanizedName:z.string().optional(),oldName:z.string().optional(),aliases:z.string().optional(),birthDate:z.string(),birthTime:z.string().nullable(),birthTimePrecision:z.enum(['exact','approximate','unknown']),birthPlace:z.object({country:z.string().optional(),region:z.string().optional(),city:z.string().optional()}),sex:z.string().optional(),language:z.string().optional(),currentLocation:z.string().optional()}),
  questions:z.array(z.string()),freeformQuestion:z.string(),requestedSystems:z.array(z.string()),options:z.object({crossAnalysis:z.boolean(),showCalculations:z.boolean(),showUncertainty:z.boolean(),generateSummaryImage:z.boolean()}).passthrough()
}).passthrough();
const Text=z.union([z.string(),z.record(z.unknown())]);
export const ResultSchema=z.object({schemaVersion:z.string(),subject:z.record(z.unknown()).default({}),meta:z.record(z.unknown()).default({}),baseInfo:z.record(z.unknown()).default({}),systems:z.array(z.object({id:z.string(),name:z.string().optional(),status:z.string().optional(),inputsUsed:z.array(z.string()).optional(),calculations:z.array(Text).optional(),facts:z.array(Text).optional(),interpretation:z.array(Text).optional(),uncertainties:z.array(z.string()).optional(),sources:z.array(Text).optional()}).passthrough()).default([]),crossAnalysis:z.object({strongThemes:z.array(Text).default([]),moderateThemes:z.array(Text).default([]),contradictions:z.array(Text).default([]),dependencyWarnings:z.array(Text).default([])}).passthrough().default({}),domainProfiles:z.record(z.unknown()).default({}),summary:z.union([z.string(),z.record(z.unknown())]).default({}),limitations:z.union([z.array(z.string()),z.record(z.unknown())]).default([]),assets:z.record(z.unknown()).default({})}).passthrough();
export type Request=z.infer<typeof RequestSchema>;export type Result=z.infer<typeof ResultSchema>;
function parseJson(text:string){try{return JSON.parse(text)}catch{throw Error('JSONを読み取れません。ファイルの形式を確認してください。')}}

export function makePrompt(r:Request,names:Record<string,string>={}){return `あなたは歴史的背景と計算根拠を区別して説明する総合占術アナリストです。添付 request.json を正確に読み、以下の仕様で鑑定してください。\n\n# 対象者\n${JSON.stringify(r.subject,null,2)}\n# 鑑定希望\n${[...r.questions,r.freeformQuestion].filter(Boolean).join('、')||'人物の資質と人生テーマ'}\n# 対象占術\n${r.requestedSystems.map(id=>names[id]||id).join('、')}\n\n出生時刻や出生地が不足する項目を推測で補わず unavailable としてください。流派差・入力精度・不確実性・計算根拠・参照資料を明記してください。複数占術が同じ生年月日などに依存する場合、独立した根拠として重複計上しないでください。Dreamspellと歴史的マヤ暦等、近代体系と古い伝統を混同しないでください。医学・法律・投資等を断定しないでください。\n\n# 成果物\nZIPで result.json、report.md、manifest.json、可能なら assets/summary.png と assets/share.png を返してください。result.json は schemaVersion "1.0.0" とし、subject/meta/baseInfo/systems/crossAnalysis (strongThemes, moderateThemes, contradictions, dependencyWarnings)/domainProfiles/summary/limitations/assets を含めます。各systems要素に id, name, status, inputsUsed, calculations, facts, interpretation, uncertainties, sources を含めてください。画像が作れない場合はmanifestに記載し、assetsは空で構いません。\n\n## report.md と画面向け要約も含む鑑定書を作成してください。`;}

export async function createRequestZip(request:Request,prompt:string,now=new Date()){const zip=new JSZip();zip.file('request.json',JSON.stringify(request,null,2));zip.file('schema/request.schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',title:'森羅万象鑑 鑑定依頼 1.0.0',type:'object',required:['schemaVersion','app','subject','questions','requestedSystems','options'],properties:{schemaVersion:{const:'1.0.0'},app:{const:'shinra-bansho-kan'},subject:{type:'object'},questions:{type:'array',items:{type:'string'}},requestedSystems:{type:'array',items:{type:'string'}},options:{type:'object'}},additionalProperties:true},null,2));zip.file('instructions.md','# 鑑定実行手順\n\nrequest.jsonを読み、指定占術を入力の範囲で解釈してください。根拠・流派差・不確実性を明記し、足りない出生情報を推測しないこと。依存関係のある体系を独立票として数えないでください。詳細な出力契約はprompt.mdを参照し、鑑定結果ZIPにresult.json・report.md・manifest.jsonを含めてください。');zip.file('prompt.md',prompt);zip.file('manifest.json',JSON.stringify({format:'shinra-bansho-request',version:'1.0.0',createdAt:now.toISOString(),files:['request.json','schema/request.schema.json','instructions.md','prompt.md','README.md']},null,2));zip.file('README.md','# 森羅万象鑑 鑑定依頼パッケージ\n\nChatGPT等にZIPを添付し、prompt.mdとinstructions.mdに従って鑑定を依頼してください。');return zip.generateAsync({type:'blob'});}

export async function parseResultBundle(file:File):Promise<Result>{let data:any;if(file.name.toLowerCase().endsWith('.zip')){const zip=await JSZip.loadAsync(file);const entry=zip.file('result.json');if(!entry){if(zip.file('request.json'))throw Error('これは鑑定依頼ZIPです。鑑定結果ZIPを選んでください。');throw Error('ZIPにresult.jsonがありません。')}const manifestFile=zip.file('manifest.json');if(manifestFile){const manifest=parseJson(await manifestFile.async('text'));if(manifest.format&&manifest.format!=='shinra-bansho-result')throw Error('manifestの形式が鑑定結果ではありません。');if(manifest.version&&!/^1\./.test(manifest.version))throw Error(`未対応の結果形式バージョンです: ${manifest.version}`)}data=parseJson(await entry.async('text'));const image=zip.file('assets/summary.png');if(image)data.assets={...(data.assets||{}),summaryImage:`data:image/png;base64,${await image.async('base64')}`};}else{data=parseJson(await file.text())}const parsed=ResultSchema.safeParse(data);if(!parsed.success)throw Error('鑑定結果の形式が不正です: '+parsed.error.issues.slice(0,3).map(i=>i.path.join('.')+' '+i.message).join(' / '));if(!/^1\./.test(parsed.data.schemaVersion))throw Error(`未対応の結果形式バージョンです: ${parsed.data.schemaVersion}`);return parsed.data;}
